// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgYJy7iA_jEBthox4rnxlXwpMMvIf9ys0',
    appId: '1:952836164485:web:4fdd81da9f186f416652ec',
    messagingSenderId: '952836164485',
    projectId: 'android-ios-29cc7',
    authDomain: 'android-ios-29cc7.firebaseapp.com',
    storageBucket: 'android-ios-29cc7.firebasestorage.app',
    measurementId: 'G-4NLCER9E9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYj4N9LWKoyFvolIy33TSjgmKI9JYnBp0',
    appId: '1:952836164485:android:1cb85aaa0d4bfc116652ec',
    messagingSenderId: '952836164485',
    projectId: 'android-ios-29cc7',
    storageBucket: 'android-ios-29cc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnc0as1xqK4hO7QO92titXjjUrWwRpVtw',
    appId: '1:952836164485:ios:c96919227c3b4f206652ec',
    messagingSenderId: '952836164485',
    projectId: 'android-ios-29cc7',
    storageBucket: 'android-ios-29cc7.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnc0as1xqK4hO7QO92titXjjUrWwRpVtw',
    appId: '1:952836164485:ios:c96919227c3b4f206652ec',
    messagingSenderId: '952836164485',
    projectId: 'android-ios-29cc7',
    storageBucket: 'android-ios-29cc7.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgYJy7iA_jEBthox4rnxlXwpMMvIf9ys0',
    appId: '1:952836164485:web:7a9b5501637387c06652ec',
    messagingSenderId: '952836164485',
    projectId: 'android-ios-29cc7',
    authDomain: 'android-ios-29cc7.firebaseapp.com',
    storageBucket: 'android-ios-29cc7.firebasestorage.app',
    measurementId: 'G-49HBV6W0KD',
  );
}
